# Generated by Django 4.0.4 on 2022-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_Number',
            field=models.IntegerField(default=0),
        ),
    ]
