# Generated by Django 4.0.4 on 2022-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('course_Number', models.PositiveIntegerField(default=0, max_length=20000)),
                ('instructor_Name', models.CharField(default='', max_length=40)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=6000)),
            ],
        ),
    ]
